FROM php:7.4-apache

RUN apt update && apt install -y nano
RUN apt install -y curl

WORKDIR /etc/apache2
RUN mkdir logs
RUN chmod a=rX logs

ENV APACHE_RUN_USER=webuser
ENV APACHE_RUN_GROUP=webgroup
ENV APACHE_LOG_DIR=logs
ENV APACHE_PID_FILE=logs/apache2.pid

RUN pecl install xdebug-3.1.6 && docker-php-ext-enable xdebug
RUN docker-php-ext-install pdo_mysql && docker-php-ext-enable pdo_mysql

COPY --link /apache2/sites-available/eXAM.conf /etc/apache2/sites-available
COPY --link /apache2/apache2.conf /etc/apache2/
COPY --link /php.ini /usr/local/etc/php/

RUN a2enmod rewrite
RUN a2ensite eXAM && a2dissite 000-default

RUN adduser -group webgroup
RUN adduser webuser 
RUN adduser webuser webgroup

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl -f http://localhost/ || exit 1