version: "3"

services:
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: Dockerfile_apache
    restart: "unless-stopped"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/eXAM/src/:ro
      - ./public:/var/www/eXAM/public/:ro
    networks:
      - backend
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: Dockerfile_mysql
    restart: "unless-stopped"
    ports:
      - "3306:3306"
    volumes:
      - mysql_conf:/etc/mysql:rw
      - mysql_data:/var/lib/mysql:rw
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_conf:
  mysql_data: